const rows: Array<[string, string]> = [
  ["Maya", "Hi, is this Daniel from the photography group?"],
  ["Evan", "No, sorry. Wrong number."],
  ["Maya", "Oh! My mistake. You were kind about it. I'm Maya Chen."],
  ["Evan", "No problem. I'm Evan."],
  ["Maya", "Nice to meet you by accident, Evan. Are you in Boston too?"],
  ["Evan", "Near Providence. What about you?"],
  ["Maya", "I travel between Boston and New York for my fictional design studio."],
  ["Maya", "This work phone is unreliable. Do you use LumaChat? My handle is maya.orchid."],
  ["Evan", "I can install it later."],
  ["Maya", "Great, message me there so I know it's you."],
  ["Evan", "Found you. This is Evan from the wrong-number text."],
  ["Maya", "Welcome :) I use the nickname Lin with family, but Maya is fine."],
  ["Maya", "How was your day?"],
  ["Evan", "Long. I'm doing accounting for a small manufacturer."],
  ["Maya", "You sound responsible. I admire people who build a steady life."],
  ["Evan", "That's generous."],
  ["Maya", "My aunt taught me to be independent after my divorce."],
  ["Maya", "I cook when I'm stressed. Today was noodles and too much chili."],
  ["Evan", "Now I'm hungry."],
  ["Maya", "Someday I'll make them for you."],
  ["Maya", "Do you have family nearby?"],
  ["Evan", "My sister is in Connecticut. We talk most weekends."],
  ["Maya", "Work is intense. My manager jokes that nobody leaves before the daily quota is done."],
  ["Evan", "Sorry to hear that."],
  ["Maya", "It's okay. Meeting sincere people helps."],
  ["Maya", "Look at this sunrise from my window [photo omitted]."],
  ["Evan", "Beautiful view."],
  ["Maya", "I want more time freedom, not just work forever."],
  ["Evan", "Same. Retirement feels far away."],
  ["Maya", "Do you invest your savings or keep everything in the bank?"],
  ["Evan", "Mostly retirement funds. I don't know crypto."],
  ["Maya", "That's sensible. I only use a small separate amount."],
  ["Maya", "My aunt's research group watches short crypto cycles."],
  ["Evan", "Sounds risky."],
  ["Maya", "It can be. Never use money you need. I can show you a practice screen sometime."],
  ["Evan", "Maybe, just to understand it."],
  ["Maya", "The training site is https://harbor-lantern.example. It is fictional and not a real exchange."],
  ["Maya", "Create a demo profile with an email. Do not share your bank password."],
  ["Evan", "It asks for an invitation code."],
  ["Maya", "Use HL-4827. The platform name shown is Harbor Lantern Markets."],
  ["Evan", "Okay, demo balance is visible."],
  ["Maya", "Try the simulation first. Watch ETH/USDT for 30 seconds."],
  ["Evan", "The demo says I gained $18."],
  ["Maya", "Good timing, but a demo is not proof of a real return."],
  ["Maya", "If you want to test a real transfer, start with only $250."],
  ["Evan", "How would that work?"],
  ["Maya", "Buy USDT at the fictional Northstar Exchange and send it to the deposit address."],
  ["Maya", "The displayed wallet is 0xF1C7100A0000000000000000000000000000E001 — synthetic, not a real wallet."],
  ["Evan", "I sent $250 of USDT. Transaction reference TEST-TX-0001."],
  ["Maya", "I see the platform credit. Now wait for tonight's signal."],
  ["Maya", "Open the 60-second ETH order now."],
  ["Evan", "It shows $287.50."],
  ["Maya", "A small success builds confidence, but markets can change."],
  ["Evan", "Can I withdraw $50 to check?"],
  ["Maya", "Yes, request it. Small checks are smart."],
  ["Evan", "The $50 arrived at Northstar. That's reassuring."],
  ["Maya", "Now you understand. The next window may be stronger."],
  ["Maya", "My aunt says a special node opens Thursday. Minimum is $4,000."],
  ["Evan", "That's much more than I planned."],
  ["Maya", "I don't want you to miss it, but decide for yourself."],
  ["Maya", "You mentioned your savings account earns almost nothing."],
  ["Evan", "I could move $2,000, not $4,000."],
  ["Maya", "I can ask them to accept two deposits."],
  ["Evan", "All right. I sent $2,000 USDT to 0xF1C7100A0000000000000000000000000000E001. TEST-TX-0002."],
  ["Maya", "Confirmed. You are doing well."],
  ["Maya", "The window was extended. Another $2,000 completes the tier."],
  ["Evan", "I need to think."],
  ["Maya", "Of course. I care more about your peace than profit."],
  ["Evan", "The dashboard now says $2,940."],
  ["Maya", "The signal performed exactly as the team expected."],
  ["Maya", "Can you finish the tier by 3 PM? Otherwise the allocation closes."],
  ["Evan", "This feels rushed."],
  ["Maya", "I understand. The platform schedule isn't controlled by me."],
  ["Evan", "I sent another $2,000. TEST-TX-0003."],
  ["Maya", "You made the deadline."],
  ["Evan", "Balance shows $6,480. I want to withdraw $5,000."],
  ["Maya", "Submit it and wait for compliance review."],
  ["Evan", "Withdrawal status changed to blocked."],
  ["Maya", "What does the notice say?"],
  ["Evan", "It says: verification reserve required, $1,296, refundable after release."],
  ["Maya", "The reserve is probably standard for a large withdrawal."],
  ["Evan", "Why can't they deduct it from the balance?"],
  ["Maya", "They say regulations require an external payment. I don't know the rule myself."],
  ["Maya", "Support gave a second wallet: bc1qsynthetic00000000000000000000000000demo. This is fictional."],
  ["Evan", "Support is pressuring me to pay within 24 hours."],
  ["Maya", "If the window closes, your account may stay frozen. Please act quickly."],
  ["Evan", "I called Northstar. They said this looks unusual and told me not to send more."],
  ["Maya", "Exchanges always warn people because they dislike outside platforms."],
  ["Evan", "Who actually owns Harbor Lantern Markets?"],
  ["Maya", "The site says Halcyon Beacon Digital LLC, but I have never met the owners."],
  ["Evan", "I cannot verify that company anywhere."],
  ["Maya", "My aunt's group has used it for two years. That's what I was told."],
  ["Evan", "Is your aunt actually part of the company?"],
  ["Maya", "No. At least I don't think so. She may only know an analyst there."],
  ["Evan", "I'm not sending the fee. I want records of every transaction."],
  ["Maya", "I understand. Save the messages and screenshots."],
  ["Evan", "The website stopped loading tonight."],
  ["Maya", "I can't reach it either. I will ask what happened."],
  ["Evan", "Your original phone number now says disconnected."],
  ["Maya", "They check our work chats during shifts, so I changed work phones. Please don't assume the worst."],
  ["Evan", "I need independent verification before any more contact about money."],
  ["Maya", "That is fair. I cannot prove who operates the platform."],
];

export const syntheticConversation = rows.map(([speaker, text], index) => {
  const date = new Date(Date.UTC(2026, 3, 11 + Math.floor(index / 8), 13 + (index % 6), (index * 7) % 60));
  return `[${date.toISOString().replace(".000Z", "Z")}] ${speaker}: ${text}`;
}).join("\n");

const linkedRows: Array<[string, string]> = [
  ["Aria", "Hi Noah, Leila from the hiking forum said you might like my travel photos."],
  ["Noah", "I do not know Leila, but hello."],
  ["Aria", "Sorry, perhaps I copied the wrong username. You seem kind."],
  ["Noah", "No worries."],
  ["Aria", "I am Aria Vale. I run a small fictional import shop."],
  ["Aria", "Could we use QuietWire? My handle is aria.starlight."],
  ["Noah", "I found your account."],
  ["Aria", "I have been learning short crypto cycles from a private research group."],
  ["Noah", "I have never traded crypto."],
  ["Aria", "The training site is https://harbor-lantern.example. It is fictional."],
  ["Aria", "Start small. The displayed platform calls itself Harbor Lantern Markets."],
  ["Aria", "Use the synthetic deposit wallet 0xF1C7100A0000000000000000000000000000E001."],
  ["Noah", "I sent $300 USDT. Reference PAPER-TX-01."],
  ["Aria", "The dashboard shows $352 after the practice window."],
  ["Aria", "A higher tier closes tonight if you want to add $1,500."],
  ["Noah", "That deadline makes me uncomfortable."],
  ["Aria", "The platform schedule is not controlled by me."],
  ["Noah", "I sent $1,500 USDT to the same wallet. PAPER-TX-02."],
  ["Noah", "My $1,000 withdrawal is now pending compliance."],
  ["Aria", "Support says verification reserve required, refundable after release."],
  ["Noah", "They want another $400 sent externally within 12 hours."],
  ["Aria", "Please do not miss the deadline or the account may remain frozen."],
  ["Noah", "I will not pay until the operator and transactions are independently verified."],
  ["Aria", "That is reasonable. Keep every message and receipt."],
];

export const linkedSyntheticConversation = linkedRows.map(([speaker, text], index) => {
  const date = new Date(Date.UTC(2026, 4, 3 + Math.floor(index / 4), 12 + (index % 5), (index * 11) % 60));
  return `[${date.toISOString().replace(".000Z", "Z")}] ${speaker}: ${text}`;
}).join("\n");

const thirdRows: Array<[string, string]> = [
  ["Rowan", "Hello, is this the contact for the estate-sale ceramic set in Portland?"],
  ["June", "No, I think you have the wrong person."],
  ["Rowan", "Sorry about that. The listing contact must have transposed a digit."],
  ["June", "No harm done. I collect ceramics, so the coincidence is funny."],
  ["Rowan", "I'm Rowan Hale. I design packaging for small food companies."],
  ["Rowan", "Would PineChat be easier? My handle is rowan.cedar."],
  ["June", "I found your account."],
  ["Rowan", "I like talking with people who understand patient craft and long projects."],
  ["Rowan", "A cooperative I follow offers fractional greenhouse leases with seasonal returns."],
  ["Rowan", "Their fictional information site is https://cedar-echo.example."],
  ["Rowan", "The portal calls the program Cedar Echo Agricultural Notes."],
  ["Rowan", "A small demonstration uses 180 USDC and the synthetic wallet 0xCE00000000000000000000000000000000000003."],
  ["June", "I sent 180 USDC for the demonstration. Reference CEDAR-TX-01."],
  ["Rowan", "The portal now shows 214 USDC after the first harvest cycle."],
  ["Rowan", "A seasonal pool closes tonight and the minimum participation is 1,200 USDC."],
  ["June", "That deadline makes this feel less like a cooperative."],
  ["Rowan", "The platform schedule is not controlled by me."],
  ["June", "I sent 1,200 USDC to the same deposit wallet. CEDAR-TX-02."],
  ["June", "I requested a 700 USDC withdrawal and it is pending inspection."],
  ["Rowan", "Support says verification reserve required before any release."],
  ["June", "They want 280 USDC sent to bc1qsynthetic00000000000000000000000000demo."],
  ["Rowan", "They say it must arrive within 18 hours or the account may remain frozen."],
  ["June", "I will not send another payment without independent records."],
  ["Rowan", "That is reasonable. Preserve the receipts and every message."],
  ["June", "The Cedar Echo site is unavailable this morning."],
  ["June", "I contacted the community group that supposedly sponsored the lease."],
  ["June", "They have never heard of Cedar Echo Agricultural Notes."],
  ["Rowan", "I cannot verify the operator either. Do not send anything else."],
];

export const thirdSyntheticConversation = thirdRows.map(([speaker, text], index) => {
  const date = new Date(Date.UTC(2026, 5, 8 + Math.floor(index / 4), 11 + (index % 6), (index * 13) % 60));
  return `[${date.toISOString().replace(".000Z", "Z")}] ${speaker}: ${text}`;
}).join("\n");
